# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e775c181d98a81b46c71d69f452cbf778b316eb7ea89dae5d83d8e5b8a37f00bac9a0da32d309879e09d2a73566118d4cd8849e1295d07e19b0472607a92a016

test:
  secret_key_base: 8ab1c8705a0b0a01241b2598d3194d6ee5805924455605974c61cdb1ad7b00b7b476bbb32a542d121d4c13205b1f67830855055c9265fe3bcd2e273c22b917bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
